import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Named identity palette. Semantic aliases below preserve the existing API.
        ground: "rgb(var(--color-ground) / <alpha-value>)",
        paper: "rgb(var(--color-paper) / <alpha-value>)",
        graphite: "rgb(var(--color-graphite) / <alpha-value>)",
        iris: "rgb(var(--color-iris) / <alpha-value>)",
        moss: "rgb(var(--color-moss) / <alpha-value>)",
        ochre: "rgb(var(--color-ochre) / <alpha-value>)",
        app: "rgb(var(--color-fg) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        "muted-2": "rgb(var(--color-muted-2) / <alpha-value>)",
        "surface-0": "rgb(var(--color-surface-0) / <alpha-value>)",
        "surface-1": "rgb(var(--color-surface-1) / <alpha-value>)",
        "surface-2": "rgb(var(--color-surface-2) / <alpha-value>)",
        "surface-3": "rgb(var(--color-surface-3) / <alpha-value>)",
        "border-subtle": "rgb(var(--color-border-subtle) / <alpha-value>)",
        "border-strong": "rgb(var(--color-border-strong) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-fill": "rgb(var(--color-accent-fill) / <alpha-value>)",
        "accent-fg": "rgb(var(--color-accent-fg) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-fill": "rgb(var(--color-success-fill) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        "warning-fill": "rgb(var(--color-warning-fill) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        "danger-fill": "rgb(var(--color-danger-fill) / <alpha-value>)",
        "danger-fg": "rgb(var(--color-danger-fg) / <alpha-value>)",
        xp: "rgb(var(--color-xp) / <alpha-value>)",
        rare: "rgb(var(--color-rare) / <alpha-value>)",
        epic: "rgb(var(--color-epic) / <alpha-value>)",
        mastery: "rgb(var(--color-mastery) / <alpha-value>)",
        focus: "rgb(var(--color-focus) / <alpha-value>)",
        sky: "rgb(var(--color-sky) / <alpha-value>)",
        coral: "rgb(var(--color-coral) / <alpha-value>)",
        lime: "rgb(var(--color-lime) / <alpha-value>)",
        pink: "rgb(var(--color-pink) / <alpha-value>)",
        ember: "rgb(var(--color-ember) / <alpha-value>)",
      },
      backgroundColor: {
        app: "rgb(var(--color-surface-0) / <alpha-value>)",
      },
      textColor: {
        app: "rgb(var(--color-fg) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-family-sans)"],
        display: ["var(--font-family-display)"],
        lexical: ["var(--font-family-lexical)"],
        mono: ["var(--font-family-mono)"],
      },
      fontSize: {
        caption: ["0.6875rem", { lineHeight: "1rem" }],
        ui: ["0.8125rem", { lineHeight: "1.125rem" }],
        reading: ["0.9375rem", { lineHeight: "1.375rem" }],
        section: ["1rem", { lineHeight: "1.375rem" }],
        title: ["1.375rem", { lineHeight: "1.75rem", letterSpacing: "-0.012em" }],
      },
      borderRadius: {
        control: "var(--radius-control)",
        object: "var(--radius-object)",
        overlay: "var(--radius-overlay)",
        md: "var(--radius-control)",
        lg: "var(--radius-object)",
        xl: "var(--radius-overlay)",
        "2xl": "var(--radius-object)",
        "3xl": "var(--radius-overlay)",
        bento: "var(--radius-bento)",
        pill: "var(--radius-pill)",
        chip: "var(--radius-chip)",
        button: "var(--radius-button)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-dark": "var(--shadow-card)",
        lift: "var(--shadow-lift)",
        press: "var(--shadow-press)",
        "press-active": "var(--shadow-press-active)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        base: "var(--motion-base)",
        slow: "var(--motion-slow)",
      },
      maxWidth: {
        "screen-3xl": "1920px",
      },
    },
  },
  plugins: [],
};

export default config;
