import "@testing-library/jest-dom/vitest";

/**
 * Stub the preload bridge for renderer tests. Tests that need realistic
 * behaviour can override individual methods with `vi.spyOn`.
 */
Object.defineProperty(window, "api", {
  value: {
    app: {
      name: "vocab-app",
      version: "0.17.3",
      platform: "test",
    },
    meta: {
      ping: async () => "pong" as const,
      appInfo: async () => ({
        name: "vocab-app",
        version: "0.17.3",
        schemaTablesExpected: 26,
        dbPath: ":memory:",
      }),
      srsArchiveStatus: async () => ({ acknowledged: true, legacyRowCount: 0 }),
    },
    auth: {
      hasPin: async () => false,
      setupPin: async () => ({ ok: true }),
      verifyPin: async () => ({ ok: true }),
      changePin: async () => ({ ok: true }),
    },
    curriculum: {
      listBooks: async () => [],
      getBookById: async () => null,
      getBookByCode: async () => null,
      listUnitsByBook: async () => [],
      getUnitById: async () => null,
      listLessonsByUnit: async () => [],
      getLessonById: async () => null,
      updateBookTitle: async () => undefined,
    },
    vocab: {
      listByLesson: async () => [],
      listFullByLesson: async () => [],
      countByLesson: async () => 0,
      getById: async () => null,
    },
    dictionary: {
      status: async () => ({
        active: false,
        packPath: null,
        entryCount: 0,
        sourceFile: null,
        files: [],
        message: null,
      }),
      search: async () => [],
      lookup: async () => null,
      batchLookup: async () => ({ entries: {} }),
      audio: async () => null,
      asset: async () => null,
      selectPackFolder: async () => ({
        active: false,
        packPath: null,
        entryCount: 0,
        sourceFile: null,
        files: [],
        message: null,
      }),
      clearPackFolder: async () => ({
        active: false,
        packPath: null,
        entryCount: 0,
        sourceFile: null,
        files: [],
        message: null,
      }),
    },
    dictionaryLearning: {
      recordSearch: async () => null,
      recordLookup: async () => ({
        id: 1,
        studentId: 1,
        dictionaryKey: "hello",
        headword: "hello",
        pos: "interjection",
        ipa: null,
        cefrLevel: null,
        definitionEn: "used as a greeting",
        definitionVi: null,
        exampleText: null,
        exampleTranslation: null,
        audioRef: null,
        status: "learning",
        stage: "flashcard",
        stability: 0,
        difficulty: 5,
        reps: 0,
        lapses: 0,
        totalCorrect: 0,
        totalWrong: 0,
        lastReviewedAt: null,
        nextDueAt: new Date(0),
        updatedAt: new Date(0),
      }),
      summary: async () => ({
        total: 0,
        due: 0,
        learning: 0,
        shortTerm: 0,
        longTerm: 0,
        averageScore: 0,
      }),
      recentSearches: async () => [],
      listItems: async () => [],
      practiceQueue: async () => [],
      recordReview: async () => ({
        item: {
          id: 1,
          studentId: 1,
          dictionaryKey: "hello",
          headword: "hello",
          pos: "interjection",
          ipa: null,
          cefrLevel: null,
          definitionEn: "used as a greeting",
          definitionVi: null,
          exampleText: null,
          exampleTranslation: null,
          audioRef: null,
          status: "short_term",
          stage: "meaning_choice",
          stability: 1,
          difficulty: 5,
          reps: 1,
          lapses: 0,
          totalCorrect: 1,
          totalWrong: 0,
          lastReviewedAt: new Date(0),
          nextDueAt: new Date(0),
          updatedAt: new Date(0),
        },
        reset: false,
        promoted: null,
      }),
    },
    grammar: {
      listByLesson: async () => [],
      listPracticeByLesson: async () => [],
      countByLesson: async () => 0,
      getById: async () => null,
    },
    students: {
      listActive: async () => [],
      listAll: async () => [],
      getById: async () => null,
      create: async (input: unknown) => input,
      update: async () => null,
      hasPin: async () => false,
      setupPin: async () => ({ ok: true }),
      verifyPin: async () => ({ ok: true }),
      changePin: async () => ({ ok: true }),
      clearPin: async () => ({ ok: true }),
      archive: async () => ({ ok: true }),
      restore: async () => ({ ok: true }),
      listAssignedBooks: async () => [],
      listAssignedUnits: async () => [],
      listAssignedUnitIds: async () => [],
      replaceUnitAssignments: async () => [],
    },
    settings: {
      get: async () => null,
      set: async () => ({ ok: true }),
      delete: async () => ({ ok: true }),
      getAll: async () => ({}),
    },
    permissions: {
      microphoneStatus: async () => ({
        platform: "test",
        status: "granted",
        granted: true,
        readyForCapture: true,
        canPrompt: false,
        canOpenSettings: false,
        requiresSystemSettings: false,
        requiresRestart: false,
        reason: null,
      }),
      requestMicrophone: async () => ({
        platform: "test",
        status: "granted",
        granted: true,
        readyForCapture: true,
        canPrompt: false,
        canOpenSettings: false,
        requiresSystemSettings: false,
        requiresRestart: false,
        reason: null,
      }),
      openMicrophoneSettings: async () => ({ opened: false }),
      logMicrophoneCaptureDiagnostic: async () => ({ ok: true }),
    },
    imports: {
      listRuns: async () => [],
      listItems: async () => [],
      uploadFile: async () => ({
        filePath: "",
        fileHash: "",
        status: "failed",
        durationMs: 0,
        stats: { inserted: 0, updated: 0, skipped: 0, failed: 0 },
        items: [],
        errors: [],
      }),
      openImportDialog: async () => ({ canceled: true, results: [] }),
    },
    progress: {
      startSession: async () => ({
        id: 1,
        studentId: 1,
        mode: "mixed",
        startedAt: new Date(0),
        endedAt: null,
        summary: null,
      }),
      endSession: async () => ({ ok: true }),
      recordAnswer: async () => ({
        event: {
          id: 1,
          studentId: 1,
          contentItemId: 1,
          sessionId: 1,
          kind: "answered_correct",
          payload: null,
          occurredAt: new Date(0),
        },
        progress: {
          studentId: 1,
          contentItemId: 1,
          track: "curated",
          stability: 1,
          difficulty: 5,
          state: "short_term",
          reps: 1,
          lapses: 0,
          lastSeenAt: new Date(0),
          nextDueAt: new Date(0),
          totalCorrect: 1,
          totalWrong: 0,
          currentStageKind: null,
          updatedAt: new Date(0),
        },
        unlockedAchievements: [],
      }),
      recordContentAnswer: async () => ({
        event: {
          id: 1,
          studentId: 1,
          contentItemId: 1,
          sessionId: 1,
          kind: "answered_correct",
          payload: null,
          occurredAt: new Date(0),
        },
        progress: {
          studentId: 1,
          contentItemId: 1,
          track: "curated",
          stability: 1,
          difficulty: 5,
          state: "short_term",
          reps: 1,
          lapses: 0,
          lastSeenAt: new Date(0),
          nextDueAt: new Date(0),
          totalCorrect: 1,
          totalWrong: 0,
          currentStageKind: null,
          updatedAt: new Date(0),
        },
        unlockedAchievements: [],
      }),
      dueByLesson: async () => ({ totalCount: 0, dueCount: 0, newCount: 0 }),
      seenEntryIdsByLesson: async () => [],
      dueByStudent: async () => [],
      studentSummary: async () => ({
        totalSeen: 0,
        totalCorrect: 0,
        totalWrong: 0,
        accuracy: 0,
        totalDue: 0,
      }),
      weakItems: async () => [],
      dailyActivity: async () => [],
      cohortActivity: async () => [],
      recentSessions: async () => [],
      unitReport: async () => [],
      unitSessions: async () => [],
      sessionReport: async () => null,
      tutorOverview: async () => [],
    },
    evidence: {
      recordEvent: async () => ({
        id: 1,
        studentId: 1,
        sessionId: 1,
        kind: "answer_submitted",
        severity: "info",
        durationMs: null,
        payload: null,
        occurredAt: new Date(0),
      }),
      recordEvents: async () => [],
      recordCameraSnapshot: async () => ({
        id: 1,
        studentId: 1,
        sessionId: 1,
        kind: "camera_snapshot",
        severity: "info",
        durationMs: null,
        payload: null,
        occurredAt: new Date(0),
      }),
      studentOverview: async () => ({
        studentId: 1,
        sessionCount: 0,
        avgAttentionScore: null,
        totalReviewFlags: 0,
        focusLossCount: 0,
        cameraSnapshotCount: 0,
        latestSessionAt: null,
        recentSessions: [],
      }),
      tutorOverview: async () => [],
      sessionTimeline: async () => null,
      exportStudentReport: async () => ({
        canceled: true,
        filePath: null,
        encrypted: false,
        sha256: "",
      }),
      importStudentData: async () => ({
        canceled: true,
        imported: false,
        studentId: null,
        stats: null,
      }),
    },
    pronunciation: {
      status: async () => ({
        available: false,
        backend: "deterministic",
        executionProvider: "cpu",
        modelFamily: "hubert",
        modelId: null,
        platform: "test",
        arch: "test",
        modelPath: null,
        modelPresent: false,
        localOnly: true,
        reason: "No offline CAPT model bundle is configured.",
      }),
      target: async (input: { text: string; ipa?: string | null }) => ({
        text: input.text,
        phonemes: input.text
          .trim()
          .toLowerCase()
          .split(/\s+/)
          .map((part) => part.replace(/[^a-z]/g, "")),
        stressPattern: [],
        source: "heuristic",
      }),
      preview: async (input: { text: string; ipa?: string | null }) => ({
        target: {
          text: input.text,
          phonemes: ["F"],
          stressPattern: [1],
          source: "heuristic",
        },
        backend: "deterministic",
        executionProvider: "cpu",
        modelUsed: false,
        durationMs: 1,
        overallScore: 88,
        phonemeScore: 90,
        stressScore: 84,
        passingScore: 70,
        errorRate: 0.12,
        retryRequired: false,
        guardrails: [],
        audioQuality: null,
        phonemes: [
          {
            phoneme: "F",
            expectedIndex: 0,
            startMs: 0,
            endMs: 40,
            score: 90,
            detectedPhoneme: "F",
            issue: "ok",
          },
        ],
        stress: {
          expectedStress: [1],
          observedStress: [1],
          score: 84,
          issue: "ok",
        },
        feedback: ["Pronunciation is clear for this target."],
      }),
      assess: async () => ({
        ok: false,
        status: {
          available: false,
          backend: "deterministic",
          executionProvider: "cpu",
          modelFamily: "hubert",
          modelId: null,
          platform: "test",
          arch: "test",
          modelPath: null,
          modelPresent: false,
          localOnly: true,
          reason: "No offline CAPT model bundle is configured.",
        },
        reason: "No offline CAPT model bundle is configured.",
      }),
    },
    rewards: {
      stats: async () => ({
        totalCorrect: 0,
        distinctCorrect: 0,
        totalAttempts: 0,
        currentStreak: 0,
        bestSessionRun: 0,
      }),
      listUnlocked: async () => [],
      streak: async () => ({
        currentStreak: 0,
        longestStreak: 0,
        lastPracticedAt: null,
        practicedToday: false,
      }),
    },
  },
  writable: true,
});

Object.defineProperty(window, "matchMedia", {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addEventListener: () => undefined,
    removeEventListener: () => undefined,
    addListener: () => undefined,
    removeListener: () => undefined,
    dispatchEvent: () => false,
  }),
});

Object.defineProperty(window, "scrollTo", {
  writable: true,
  value: () => undefined,
});

Object.defineProperty(HTMLElement.prototype, "scrollIntoView", {
  writable: true,
  value: () => undefined,
});
