import { Modal } from "@/ui/components/Modal";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { useId } from "react";
import { describe, expect, it, vi } from "vitest";

describe("Modal", () => {
  it("does not render when open=false", () => {
    render(
      <Modal open={false} onClose={() => undefined} title="Hidden">
        <p>body</p>
      </Modal>,
    );
    expect(screen.queryByRole("dialog")).toBeNull();
  });

  it("renders a labelled dialog when open", () => {
    render(
      <Modal open onClose={() => undefined} title="Add student">
        <p>body</p>
      </Modal>,
    );
    const dialog = screen.getByRole("dialog", { name: "Add student" });
    expect(dialog).toHaveAttribute("aria-modal", "true");
    expect(dialog).toHaveAttribute("aria-labelledby");
  });

  it("calls onClose when Escape is pressed", () => {
    const onClose = vi.fn();
    render(
      <Modal open onClose={onClose} title="X">
        <p>body</p>
      </Modal>,
    );
    fireEvent.keyDown(document, { key: "Escape" });
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("calls onClose when the backdrop is clicked", () => {
    const onClose = vi.fn();
    render(
      <Modal open onClose={onClose} title="X">
        <p>body</p>
      </Modal>,
    );
    fireEvent.click(screen.getByRole("button", { name: /close dialog/i }));
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("renders the footer when provided", () => {
    render(
      <Modal open onClose={() => undefined} title="X" footer={<button type="button">Save</button>}>
        <p>body</p>
      </Modal>,
    );
    expect(screen.getByRole("button", { name: "Save" })).toBeInTheDocument();
    expect(screen.getByRole("dialog")).toHaveClass("max-h-[calc(100dvh-5rem)]");
    expect(document.querySelector("[data-modal-body]")).toHaveClass("overflow-y-auto");
  });

  it("keeps keyboard focus inside the dialog", () => {
    render(
      <Modal
        open
        onClose={() => undefined}
        title="Focus test"
        footer={<button type="button">Save</button>}
      >
        <button type="button">First</button>
      </Modal>,
    );
    const first = screen.getByRole("button", { name: "First" });
    const last = screen.getByRole("button", { name: "Save" });
    last.focus();
    fireEvent.keyDown(document, { key: "Tab" });
    expect(first).toHaveFocus();
  });

  it("focuses ids generated by React without treating colons as selector syntax", async () => {
    function GeneratedIdForm() {
      const inputId = useId();
      return (
        <Modal open onClose={() => undefined} title="Generated id" initialFocusId={inputId}>
          <input id={inputId} aria-label="Generated field" />
        </Modal>
      );
    }

    render(<GeneratedIdForm />);
    await waitFor(() => expect(screen.getByLabelText("Generated field")).toHaveFocus());
  });

  it("skips visually hidden controls when choosing initial focus", async () => {
    render(
      <Modal open onClose={() => undefined} title="Visible focus">
        <span style={{ display: "none" }}>
          <input aria-label="Hidden upload" />
        </span>
        <button type="button">Visible action</button>
      </Modal>,
    );

    await waitFor(() =>
      expect(screen.getByRole("button", { name: "Visible action" })).toHaveFocus(),
    );
  });

  it("moves focus back inside when it escapes the active dialog", async () => {
    render(
      <>
        <button type="button">Outside</button>
        <Modal open onClose={() => undefined} title="Contained focus">
          <button type="button">Inside</button>
        </Modal>
      </>,
    );
    const inside = screen.getByRole("button", { name: "Inside" });
    await waitFor(() => expect(inside).toHaveFocus());

    screen.getByRole("button", { name: "Outside" }).focus();
    expect(inside).toHaveFocus();
  });

  it("uses the latest close callback without restarting the open-dialog lifecycle", async () => {
    const firstOnClose = vi.fn();
    const latestOnClose = vi.fn();
    const { rerender } = render(
      <Modal open onClose={firstOnClose} title="Stable lifecycle">
        <input aria-label="Active field" />
      </Modal>,
    );
    const input = screen.getByRole("textbox", { name: "Active field" });
    await waitFor(() => expect(input).toHaveFocus());

    rerender(
      <Modal open onClose={latestOnClose} title="Stable lifecycle">
        <input aria-label="Active field" />
      </Modal>,
    );
    expect(input).toHaveFocus();
    fireEvent.keyDown(document, { key: "Escape" });
    expect(firstOnClose).not.toHaveBeenCalled();
    expect(latestOnClose).toHaveBeenCalledTimes(1);
  });

  it("gives Escape, focus and scroll ownership only to the topmost dialog", async () => {
    const firstOnClose = vi.fn();
    const secondOnClose = vi.fn();
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "auto";

    const renderDialogs = (firstOpen: boolean, secondOpen: boolean) => (
      <>
        <Modal open={firstOpen} onClose={firstOnClose} title="First dialog">
          <button type="button">First action</button>
        </Modal>
        <Modal open={secondOpen} onClose={secondOnClose} title="Second dialog">
          <button type="button">Second action</button>
        </Modal>
      </>
    );

    const { rerender } = render(renderDialogs(true, false));
    const firstAction = screen.getByRole("button", { name: "First action" });
    await waitFor(() => expect(firstAction).toHaveFocus());

    rerender(renderDialogs(true, true));
    const secondAction = screen.getByRole("button", { name: "Second action" });
    await waitFor(() => expect(secondAction).toHaveFocus());
    expect(firstAction.closest("[data-dialog-surface]")).toHaveAttribute("aria-hidden", "true");
    expect(firstAction.closest("[data-dialog-surface]")).toHaveAttribute("inert");

    fireEvent.keyDown(document, { key: "Escape" });
    expect(firstOnClose).not.toHaveBeenCalled();
    expect(secondOnClose).toHaveBeenCalledTimes(1);
    expect(document.body).toHaveStyle({ overflow: "hidden" });

    rerender(renderDialogs(true, false));
    await waitFor(() => expect(firstAction).toHaveFocus());
    expect(firstAction.closest("[data-dialog-surface]")).not.toHaveAttribute("aria-hidden");
    expect(document.body).toHaveStyle({ overflow: "hidden" });

    rerender(renderDialogs(false, false));
    expect(document.body).toHaveStyle({ overflow: "auto" });
    document.body.style.overflow = previousOverflow;
  });

  it("makes the app window inert only while a dialog is open", () => {
    const { rerender } = render(
      <div data-app-window data-testid="app-window">
        <button type="button">Background action</button>
        <Modal open onClose={() => undefined} title="Foreground dialog">
          <button type="button">Dialog action</button>
        </Modal>
      </div>,
    );
    const appWindow = screen.getByTestId("app-window");
    expect(appWindow).toHaveAttribute("aria-hidden", "true");
    expect(appWindow).toHaveAttribute("inert");

    rerender(
      <div data-app-window data-testid="app-window">
        <button type="button">Background action</button>
        <Modal open={false} onClose={() => undefined} title="Foreground dialog">
          <button type="button">Dialog action</button>
        </Modal>
      </div>,
    );
    expect(screen.getByTestId("app-window")).not.toHaveAttribute("aria-hidden");
    expect(screen.getByTestId("app-window")).not.toHaveAttribute("inert");
  });
});
